# Generated by Django 4.0.6 on 2022-07-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('condition', models.IntegerField(choices=[(1, 'new'), (2, 'used')], default='new')),
                ('fuel', models.IntegerField(choices=[(1, 'Gasoline'), (2, 'Diesel'), (3, 'Gas'), (4, 'Electro'), (4, 'Hybrid')], default='Gasoline')),
                ('price', models.FloatField()),
                ('currency', models.IntegerField(choices=[(1, 'EURO'), (2, 'USD')], default='EURO')),
                ('vehicle_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Motorcycle')], default='Car')),
                ('classification', models.IntegerField(choices=[(1, 'Modern'), (2, 'Classic'), (3, 'Antique'), (4, 'Vintage')], default='Modern')),
                ('km_traveled', models.FloatField()),
                ('year', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='brands.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/vehicles/%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
        ),
    ]
