# Generated by Django 4.0.6 on 2022-07-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle',
            new_name='brand_model',
        ),
    ]
