version: "3.8"

services:
  django:
    build: ./django-backend
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./django-backend:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db

  react:
    build: ./react-frontend
    container_name: react
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ./entrypoint.sh

  db:
    image: mysql:latest
    container_name: db
    env_file:
      - ./.env
    restart: always
