version: "3.8"

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_ROOT_PASSWORD=mysql-root-password
    depends_on:
      - db

  react:
    build: ./react-app
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_ROOT_PASSWORD=mysql-root-password
    ports:
      - "3306:3306"
    restart: always

volumes:
  pgdata:
