version: "3.8"

services:
  nginx_auto_website:
    image: nginx:latest
    ports:
      - "83:80"
    volumes:
      - ./nginx/nginx.${NGINX_ENV}.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/app/static/
      - media:/app/media/
      - ./react-frontend/build/:/app/frontend/
    depends_on:
      - django_auto_website

  django_auto_website:
    build: ./django-backend
    container_name: django_auto_website
    ports:
      - "8000:8000"
    volumes:
      - ./django-backend:/usr/src/app/
      - static:/usr/src/app/out/
      - media:/usr/src/app/media/
    env_file:
      - ./.env
    depends_on:
      - db_auto_website

  react_auto_website:
    build: ./react-frontend
    container_name: react_auto_website
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ./entrypoint.sh

  db_auto_website:
    image: mysql:latest
    container_name: db_auto_website
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    restart: always

volumes:
  static:
  media: