version: "3.8"

services:
  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
      - media:/usr/src/app/media
      - static:/usr/src/app/out
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_ROOT_PASSWORD=mysql-root-password
    depends_on:
      - db

  react:
    build: ./react-app
    container_name: react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=
      - REACT_APP_API_URL=/api
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_ROOT_PASSWORD=mysql-root-password
    restart: always

  nginx:
    image: nginx:8.0
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media:/usr/src/app/media/
      - static:/usr/src/app/static/
    depends_on:
      - django
      - react

volumes:
  pgdata:
  media:
  static:
